type: segment_anything
name: segment_anything_vit_b_textile
display_name: Segment Anything (TextileSAM)
decoder_model_path: textilesam_vit_b.decoder.onnx
encoder_model_path: textilesam_vit_b.encoder.onnx
input_size: 1024
max_height: 1024
max_width: 4096
